const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const source=fs.readFileSync('runtime/script.js','utf8');
function setup(fetcher=async()=>({})) {
 const nodes=new Map(); const node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',innerHTML:'',textContent:'',hidden:false,removeAttribute(k){delete this[k]},querySelector(s){return node(id+s)}});return nodes.get(id)};
 const state={missingRows:[],missingSummary:{scannedAt:'2026-09-18',scannedSeries:5},missingScannedOnce:true,missingWarnings:[],config:{}};
 const elements={missingList:node('list'),missingFeedback:node('feedback'),missingScanBtn:node('scan'),missingSearch:node('search'),missingStatus:node('filter')};elements.missingStatus.value='all';
 const ctx={appState:state,elements,document:{getElementById:node},formatDate:String,escapeHtml:s=>String(s).replaceAll('<','&lt;'),buildEmbyPrimaryPosterUrl:()=>'',inviteApiFetch:fetcher,URLSearchParams,window:{setTimeout:r=>r()},addSyncEvent:()=>{}};
 vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('let missingListRequest'),source.indexOf('function persistLocalState'))+';this.api={renderMissing,missingNotice,loadMissingList,pollMissingScanStatus,resumeMissingScanIfRunning};',ctx);
 return {state,elements,node,api:ctx.api};
}
test('filtered empty state never claims library is complete',()=>{const c=setup();c.elements.missingSearch.value='notfound';c.api.renderMissing();assert(c.elements.missingList.innerHTML.includes('没有符合条件'));assert(!c.elements.missingList.innerHTML.includes('未发现需要处理'));});
test('persistent failure notice survives renders and lists all warnings',()=>{const c=setup();c.state.missingWarnings=['one','two'];c.api.missingNotice('巡检失败');c.api.renderMissing();assert.equal(c.elements.missingFeedback.textContent,'巡检失败');assert(c.node('missing-warningsul').innerHTML.includes('two'));});
test('cards use a dialog trigger and do not embed expanded episode lists',()=>{const c=setup();c.state.missingRows=[{seriesName:'<unsafe>',status:'review',seasonRows:[]}];c.api.renderMissing();const html=c.elements.missingList.innerHTML;assert(html.includes('data-missing-detail="0"'));assert(!html.includes('<details'));assert(!html.includes('<unsafe>'));});
test('late search response does not replace newest result',async()=>{const r=[];const c=setup(()=>new Promise(resolve=>r.push(resolve)));const a=c.api.loadMissingList();const b=c.api.loadMissingList();r[1]({rows:[{seriesName:'new'}]});await b;r[0]({rows:[{seriesName:'old'}]});await a;assert.equal(c.state.missingRows[0].seriesName,'new');});
test('failed background job is visible after polling ends',async()=>{const c=setup(async()=>({status:{running:false,error:'TMDB timeout'}}));await c.api.pollMissingScanStatus();c.api.renderMissing();assert(c.elements.missingFeedback.textContent.includes('TMDB timeout'));assert.equal(c.elements.missingScanBtn.disabled,false);});
test('poll transport error preserves running status until server confirms completion',async()=>{const c=setup(async()=>{throw Error('offline')});c.state.missingLoading=true;await c.api.pollMissingScanStatus();assert.equal(c.state.missingLoading,true);assert(c.elements.missingFeedback.textContent.includes('offline'));});
test('refresh resumes and clears stale running state when backend finished',async()=>{const c=setup(async()=>({status:{running:false}}));c.state.missingLoading=true;await c.api.resumeMissingScanIfRunning();assert.equal(c.state.missingLoading,false);});

const detail=fs.readFileSync('runtime/missing-detail.js','utf8');
const detailApi=vm.runInNewContext(detail+';({missingDetailLabels,missingDetailContent})',{escapeHtml:s=>String(s).replaceAll('<','&lt;')});
test('dialog shows full episode set and filters season without cross-season leakage',()=>{const row={status:'missing',missingLabels:Array.from({length:40},(_,i)=>`S01E${i+1}`).concat(['S02E01']),seasonRows:[]};assert(detailApi.missingDetailContent(row).includes('S01E40'));assert.equal(detailApi.missingDetailLabels(row,'missing','2').join(','),'S02E01');assert(!detailApi.missingDetailContent(row,'2').includes('S01E40'));});
test('review never exposes unconfirmed labels as confirmed missing or copyable',()=>{const row={status:'review',missingLabels:['S01E01'],referenceMissingLabels:['S01E01'],seasonRows:[{seasonNo:1}]};assert.equal(detailApi.missingDetailLabels(row,'missing').length,0);assert(detailApi.missingDetailContent(row).includes('待核对'));assert.equal(detailApi.missingDetailLabels(row,'reference').length,1);});
